DROP TABLE IF EXISTS `progression_world`.`npc_text`;
CREATE TABLE `progression_world`.`npc_text` (
    `ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
    `Patch` INT UNSIGNED NOT NULL DEFAULT '0',
    `text0_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text0_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID0` INT(10) NOT NULL DEFAULT '0',
    `lang0` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability0` FLOAT NOT NULL DEFAULT '0',
    `em0_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em0_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em0_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em0_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em0_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em0_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text1_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text1_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID1` INT(10) NOT NULL DEFAULT '0',
    `lang1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability1` FLOAT NOT NULL DEFAULT '0',
    `em1_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em1_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em1_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em1_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em1_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em1_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text2_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text2_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID2` INT(10) NOT NULL DEFAULT '0',
    `lang2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability2` FLOAT NOT NULL DEFAULT '0',
    `em2_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em2_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em2_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em2_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em2_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em2_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text3_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text3_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID3` INT(10) NOT NULL DEFAULT '0',
    `lang3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability3` FLOAT NOT NULL DEFAULT '0',
    `em3_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em3_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em3_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em3_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em3_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em3_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text4_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text4_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID4` INT(10) NOT NULL DEFAULT '0',
    `lang4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability4` FLOAT NOT NULL DEFAULT '0',
    `em4_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em4_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em4_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em4_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em4_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em4_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text5_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text5_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID5` INT(10) NOT NULL DEFAULT '0',
    `lang5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability5` FLOAT NOT NULL DEFAULT '0',
    `em5_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em5_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em5_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em5_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em5_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em5_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text6_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text6_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID6` INT(10) NOT NULL DEFAULT '0',
    `lang6` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability6` FLOAT NOT NULL DEFAULT '0',
    `em6_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em6_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em6_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em6_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em6_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em6_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `text7_0` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `text7_1` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `BroadcastTextID7` INT(10) NOT NULL DEFAULT '0',
    `lang7` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
    `Probability7` FLOAT NOT NULL DEFAULT '0',
    `em7_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em7_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em7_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em7_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em7_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `em7_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
    `VerifiedBuild` INT(10) NULL DEFAULT NULL,
    PRIMARY KEY (`ID`, `Patch`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

INSERT INTO `progression_world`.`npc_text`
SELECT `ID`, 17 AS `Patch`, `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`, `text1_0`, `text1_1`, `BroadcastTextID1`, `lang1`, `Probability1`, `em1_0`, `em1_1`, `em1_2`, `em1_3`, `em1_4`, `em1_5`, `text2_0`, `text2_1`, `BroadcastTextID2`, `lang2`, `Probability2`, `em2_0`, `em2_1`, `em2_2`, `em2_3`, `em2_4`, `em2_5`, `text3_0`, `text3_1`, `BroadcastTextID3`, `lang3`, `Probability3`, `em3_0`, `em3_1`, `em3_2`, `em3_3`, `em3_4`, `em3_5`, `text4_0`, `text4_1`, `BroadcastTextID4`, `lang4`, `Probability4`, `em4_0`, `em4_1`, `em4_2`, `em4_3`, `em4_4`, `em4_5`, `text5_0`, `text5_1`, `BroadcastTextID5`, `lang5`, `Probability5`, `em5_0`, `em5_1`, `em5_2`, `em5_3`, `em5_4`, `em5_5`, `text6_0`, `text6_1`, `BroadcastTextID6`, `lang6`, `Probability6`, `em6_0`, `em6_1`, `em6_2`, `em6_3`, `em6_4`, `em6_5`, `text7_0`, `text7_1`, `BroadcastTextID7`, `lang7`, `Probability7`, `em7_0`, `em7_1`, `em7_2`, `em7_3`, `em7_4`, `em7_5`, `VerifiedBuild` FROM `base_world`.`npc_text` WHERE `ID` IN (
    5480 -- Thamarian
) UNION SELECT `ID`, 12 AS `Patch`, 'On the northern dock, you can board a ship that will carry you to Rut\'theran Village and Darnassus. From the southern dock, you can find passage across the Great Sea to Menethil Harbor on Khaz Modan. The dock to the west, at the end of the pier, leads to Azuremyst Isle, near the Exodar. Safe journeys to you!' AS `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`, `text1_0`, `text1_1`, `BroadcastTextID1`, `lang1`, `Probability1`, `em1_0`, `em1_1`, `em1_2`, `em1_3`, `em1_4`, `em1_5`, `text2_0`, `text2_1`, `BroadcastTextID2`, `lang2`, `Probability2`, `em2_0`, `em2_1`, `em2_2`, `em2_3`, `em2_4`, `em2_5`, `text3_0`, `text3_1`, `BroadcastTextID3`, `lang3`, `Probability3`, `em3_0`, `em3_1`, `em3_2`, `em3_3`, `em3_4`, `em3_5`, `text4_0`, `text4_1`, `BroadcastTextID4`, `lang4`, `Probability4`, `em4_0`, `em4_1`, `em4_2`, `em4_3`, `em4_4`, `em4_5`, `text5_0`, `text5_1`, `BroadcastTextID5`, `lang5`, `Probability5`, `em5_0`, `em5_1`, `em5_2`, `em5_3`, `em5_4`, `em5_5`, `text6_0`, `text6_1`, `BroadcastTextID6`, `lang6`, `Probability6`, `em6_0`, `em6_1`, `em6_2`, `em6_3`, `em6_4`, `em6_5`, `text7_0`, `text7_1`, `BroadcastTextID7`, `lang7`, `Probability7`, `em7_0`, `em7_1`, `em7_2`, `em7_3`, `em7_4`, `em7_5`, `VerifiedBuild` FROM `base_world`.`npc_text` WHERE `ID` IN (
    5480 -- Thamarian
) UNION SELECT `ID`, 0 AS `Patch`, 'On the northern dock, you can board a ship that will carry you to Rut\'theran Village and Darnassus.  From the southern dock, you can find passage across the Great Sea to Menethil Harbor on Khaz Modan. Safe journeys to you!' AS `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`, `text1_0`, `text1_1`, `BroadcastTextID1`, `lang1`, `Probability1`, `em1_0`, `em1_1`, `em1_2`, `em1_3`, `em1_4`, `em1_5`, `text2_0`, `text2_1`, `BroadcastTextID2`, `lang2`, `Probability2`, `em2_0`, `em2_1`, `em2_2`, `em2_3`, `em2_4`, `em2_5`, `text3_0`, `text3_1`, `BroadcastTextID3`, `lang3`, `Probability3`, `em3_0`, `em3_1`, `em3_2`, `em3_3`, `em3_4`, `em3_5`, `text4_0`, `text4_1`, `BroadcastTextID4`, `lang4`, `Probability4`, `em4_0`, `em4_1`, `em4_2`, `em4_3`, `em4_4`, `em4_5`, `text5_0`, `text5_1`, `BroadcastTextID5`, `lang5`, `Probability5`, `em5_0`, `em5_1`, `em5_2`, `em5_3`, `em5_4`, `em5_5`, `text6_0`, `text6_1`, `BroadcastTextID6`, `lang6`, `Probability6`, `em6_0`, `em6_1`, `em6_2`, `em6_3`, `em6_4`, `em6_5`, `text7_0`, `text7_1`, `BroadcastTextID7`, `lang7`, `Probability7`, `em7_0`, `em7_1`, `em7_2`, `em7_3`, `em7_4`, `em7_5`, `VerifiedBuild` FROM `base_world`.`npc_text` WHERE `ID` IN (
    5480 -- Thamarian
);
